// src/main/webapp/app/entities/categorie/categorie-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="syndicWebApp.categorie.home.createOrEditLabel"
          data-cy="CategorieCreateUpdateHeading"
          v-text="$t('syndicWebApp.categorie.home.createOrEditLabel')"
        >
          Create or edit a Categorie
        </h2>
        <div>
          <div class="form-group" v-if="categorie.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="categorie.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('syndicWebApp.categorie.libelle')" for="categorie-libelle">Libelle</label>
            <input
              type="text"
              class="form-control"
              name="libelle"
              id="categorie-libelle"
              data-cy="libelle"
              :class="{ valid: !$v.categorie.libelle.$invalid, invalid: $v.categorie.libelle.$invalid }"
              v-model="$v.categorie.libelle.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('syndicWebApp.categorie.depense')" for="categorie-depense">Depense</label>
            <select class="form-control" id="categorie-depense" data-cy="depense" name="depense" v-model="categorie.depense">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="categorie.depense && depenseOption.id === categorie.depense.id ? categorie.depense : depenseOption"
                v-for="depenseOption in depenses"
                :key="depenseOption.id"
              >
                {{ depenseOption.id }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('syndicWebApp.categorie.revenu')" for="categorie-revenu">Revenu</label>
            <select class="form-control" id="categorie-revenu" data-cy="revenu" name="revenu" v-model="categorie.revenu">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="categorie.revenu && revenuOption.id === categorie.revenu.id ? categorie.revenu : revenuOption"
                v-for="revenuOption in revenus"
                :key="revenuOption.id"
              >
                {{ revenuOption.id }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.categorie.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./categorie-update.component.ts"></script>

// src/main/webapp/app/entities/categorie/categorie-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IDepense } from 'app/shared/model/depense.model';
import { getEntities as getDepenses } from 'app/entities/depense/depense.reducer';
import { IRevenu } from 'app/shared/model/revenu.model';
import { getEntities as getRevenus } from 'app/entities/revenu/revenu.reducer';
import { ICategorie } from 'app/shared/model/categorie.model';
import { getEntity, updateEntity, createEntity, reset } from './categorie.reducer';

export const CategorieUpdate = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const depenses = useAppSelector(state => state.depense.entities);
  const revenus = useAppSelector(state => state.revenu.entities);
  const categorieEntity = useAppSelector(state => state.categorie.entity);
  const loading = useAppSelector(state => state.categorie.loading);
  const updating = useAppSelector(state => state.categorie.updating);
  const updateSuccess = useAppSelector(state => state.categorie.updateSuccess);
  const handleClose = () => {
    props.history.push('/categorie');
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(props.match.params.id));
    }

    dispatch(getDepenses({}));
    dispatch(getRevenus({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    const entity = {
      ...categorieEntity,
      ...values,
      depense: depenses.find(it => it.id.toString() === values.depense.toString()),
      revenu: revenus.find(it => it.id.toString() === values.revenu.toString()),
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {}
      : {
          ...categorieEntity,
          depense: categorieEntity?.depense?.id,
          revenu: categorieEntity?.revenu?.id,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="syndicWebApp.categorie.home.createOrEditLabel" data-cy="CategorieCreateUpdateHeading">
            <Translate contentKey="syndicWebApp.categorie.home.createOrEditLabel">Create or edit a Categorie</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="categorie-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label={translate('syndicWebApp.categorie.libelle')}
                id="categorie-libelle"
                name="libelle"
                data-cy="libelle"
                type="text"
              />
              <ValidatedField
                id="categorie-depense"
                name="depense"
                data-cy="depense"
                label={translate('syndicWebApp.categorie.depense')}
                type="select"
              >
                <option value="" key="0" />
                {depenses
                  ? depenses.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <ValidatedField
                id="categorie-revenu"
                name="revenu"
                data-cy="revenu"
                label={translate('syndicWebApp.categorie.revenu')}
                type="select"
              >
                <option value="" key="0" />
                {revenus
                  ? revenus.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/categorie" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default CategorieUpdate;
