// src/main/webapp/app/entities/payement/payement.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IPayement } from 'app/shared/model/payement.model';
import { getEntities } from './payement.reducer';

export const Payement = (props: RouteComponentProps<{ url: string }>) => {
  const dispatch = useAppDispatch();

  const payementList = useAppSelector(state => state.payement.entities);
  const loading = useAppSelector(state => state.payement.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  const { match } = props;

  return (
    <div>
      <h2 id="payement-heading" data-cy="PayementHeading">
        <Translate contentKey="syndicWebApp.payement.home.title">Payements</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="syndicWebApp.payement.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/payement/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="syndicWebApp.payement.home.createLabel">Create new Payement</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {payementList && payementList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="syndicWebApp.payement.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="syndicWebApp.payement.montant">Montant</Translate>
                </th>
                <th>
                  <Translate contentKey="syndicWebApp.payement.date">Date</Translate>
                </th>
                <th>
                  <Translate contentKey="syndicWebApp.payement.description">Description</Translate>
                </th>
                <th>
                  <Translate contentKey="syndicWebApp.payement.appartement">Appartement</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {payementList.map((payement, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/payement/${payement.id}`} color="link" size="sm">
                      {payement.id}
                    </Button>
                  </td>
                  <td>{payement.montant}</td>
                  <td>{payement.date ? <TextFormat type="date" value={payement.date} format={APP_LOCAL_DATE_FORMAT} /> : null}</td>
                  <td>{payement.description}</td>
                  <td>
                    {payement.appartement ? <Link to={`/appartement/${payement.appartement.id}`}>{payement.appartement.id}</Link> : ''}
                  </td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/payement/${payement.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/payement/${payement.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/payement/${payement.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="syndicWebApp.payement.home.notFound">No Payements found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default Payement;

// src/main/webapp/app/entities/payement/payement.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="PayementHeading">
      <span v-text="$t('syndicWebApp.payement.home.title')" id="payement-heading">Payements</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('syndicWebApp.payement.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'PayementCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-payement"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('syndicWebApp.payement.home.createLabel')"> Create a new Payement </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && payements && payements.length === 0">
      <span v-text="$t('syndicWebApp.payement.home.notFound')">No payements found</span>
    </div>
    <div class="table-responsive" v-if="payements && payements.length > 0">
      <table class="table table-striped" aria-describedby="payements">
        <thead>
          <tr>
            <th scope="row"><span v-text="$t('global.field.id')">ID</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.payement.montant')">Montant</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.payement.date')">Date</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.payement.description')">Description</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.payement.appartement')">Appartement</span></th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="payement in payements" :key="payement.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'PayementView', params: { payementId: payement.id } }">{{ payement.id }}</router-link>
            </td>
            <td>{{ payement.montant }}</td>
            <td>{{ payement.date }}</td>
            <td>{{ payement.description }}</td>
            <td>
              <div v-if="payement.appartement">
                <router-link :to="{ name: 'AppartementView', params: { appartementId: payement.appartement.id } }">{{
                  payement.appartement.id
                }}</router-link>
              </div>
            </td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'PayementView', params: { payementId: payement.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'PayementEdit', params: { payementId: payement.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(payement)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span id="syndicWebApp.payement.delete.question" data-cy="payementDeleteDialogHeading" v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-payement-heading" v-text="$t('syndicWebApp.payement.delete.question', { id: removeId })">
          Are you sure you want to delete this Payement?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-payement"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removePayement()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./payement.component.ts"></script>
