// src/main/webapp/app/entities/appartement/appartement-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IResident } from 'app/shared/model/resident.model';
import { getEntities as getResidents } from 'app/entities/resident/resident.reducer';
import { IImmeuble } from 'app/shared/model/immeuble.model';
import { getEntities as getImmeubles } from 'app/entities/immeuble/immeuble.reducer';
import { IAppartement } from 'app/shared/model/appartement.model';
import { getEntity, updateEntity, createEntity, reset } from './appartement.reducer';

export const AppartementUpdate = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const residents = useAppSelector(state => state.resident.entities);
  const immeubles = useAppSelector(state => state.immeuble.entities);
  const appartementEntity = useAppSelector(state => state.appartement.entity);
  const loading = useAppSelector(state => state.appartement.loading);
  const updating = useAppSelector(state => state.appartement.updating);
  const updateSuccess = useAppSelector(state => state.appartement.updateSuccess);
  const handleClose = () => {
    props.history.push('/appartement');
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(props.match.params.id));
    }

    dispatch(getResidents({}));
    dispatch(getImmeubles({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    const entity = {
      ...appartementEntity,
      ...values,
      resident: residents.find(it => it.id.toString() === values.resident.toString()),
      immeuble: immeubles.find(it => it.id.toString() === values.immeuble.toString()),
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {}
      : {
          ...appartementEntity,
          resident: appartementEntity?.resident?.id,
          immeuble: appartementEntity?.immeuble?.id,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="syndicWebApp.appartement.home.createOrEditLabel" data-cy="AppartementCreateUpdateHeading">
            <Translate contentKey="syndicWebApp.appartement.home.createOrEditLabel">Create or edit a Appartement</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="appartement-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label={translate('syndicWebApp.appartement.numero')}
                id="appartement-numero"
                name="numero"
                data-cy="numero"
                type="text"
              />
              <ValidatedField
                label={translate('syndicWebApp.appartement.etage')}
                id="appartement-etage"
                name="etage"
                data-cy="etage"
                type="text"
              />
              <ValidatedField
                label={translate('syndicWebApp.appartement.surface')}
                id="appartement-surface"
                name="surface"
                data-cy="surface"
                type="text"
              />
              <ValidatedField
                id="appartement-resident"
                name="resident"
                data-cy="resident"
                label={translate('syndicWebApp.appartement.resident')}
                type="select"
              >
                <option value="" key="0" />
                {residents
                  ? residents.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <ValidatedField
                id="appartement-immeuble"
                name="immeuble"
                data-cy="immeuble"
                label={translate('syndicWebApp.appartement.immeuble')}
                type="select"
              >
                <option value="" key="0" />
                {immeubles
                  ? immeubles.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/appartement" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default AppartementUpdate;

// src/main/webapp/app/entities/appartement/appartement-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="syndicWebApp.appartement.home.createOrEditLabel"
          data-cy="AppartementCreateUpdateHeading"
          v-text="$t('syndicWebApp.appartement.home.createOrEditLabel')"
        >
          Create or edit a Appartement
        </h2>
        <div>
          <div class="form-group" v-if="appartement.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="appartement.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('syndicWebApp.appartement.numero')" for="appartement-numero">Numero</label>
            <input
              type="number"
              class="form-control"
              name="numero"
              id="appartement-numero"
              data-cy="numero"
              :class="{ valid: !$v.appartement.numero.$invalid, invalid: $v.appartement.numero.$invalid }"
              v-model.number="$v.appartement.numero.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('syndicWebApp.appartement.etage')" for="appartement-etage">Etage</label>
            <input
              type="number"
              class="form-control"
              name="etage"
              id="appartement-etage"
              data-cy="etage"
              :class="{ valid: !$v.appartement.etage.$invalid, invalid: $v.appartement.etage.$invalid }"
              v-model.number="$v.appartement.etage.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('syndicWebApp.appartement.surface')" for="appartement-surface">Surface</label>
            <input
              type="number"
              class="form-control"
              name="surface"
              id="appartement-surface"
              data-cy="surface"
              :class="{ valid: !$v.appartement.surface.$invalid, invalid: $v.appartement.surface.$invalid }"
              v-model.number="$v.appartement.surface.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('syndicWebApp.appartement.resident')" for="appartement-resident">Resident</label>
            <select class="form-control" id="appartement-resident" data-cy="resident" name="resident" v-model="appartement.resident">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="appartement.resident && residentOption.id === appartement.resident.id ? appartement.resident : residentOption"
                v-for="residentOption in residents"
                :key="residentOption.id"
              >
                {{ residentOption.id }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('syndicWebApp.appartement.immeuble')" for="appartement-immeuble">Immeuble</label>
            <select class="form-control" id="appartement-immeuble" data-cy="immeuble" name="immeuble" v-model="appartement.immeuble">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="appartement.immeuble && immeubleOption.id === appartement.immeuble.id ? appartement.immeuble : immeubleOption"
                v-for="immeubleOption in immeubles"
                :key="immeubleOption.id"
              >
                {{ immeubleOption.id }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.appartement.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./appartement-update.component.ts"></script>
