// src/main/webapp/app/entities/immeuble/immeuble.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="ImmeubleHeading">
      <span v-text="$t('syndicWebApp.immeuble.home.title')" id="immeuble-heading">Immeubles</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('syndicWebApp.immeuble.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'ImmeubleCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-immeuble"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('syndicWebApp.immeuble.home.createLabel')"> Create a new Immeuble </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && immeubles && immeubles.length === 0">
      <span v-text="$t('syndicWebApp.immeuble.home.notFound')">No immeubles found</span>
    </div>
    <div class="table-responsive" v-if="immeubles && immeubles.length > 0">
      <table class="table table-striped" aria-describedby="immeubles">
        <thead>
          <tr>
            <th scope="row"><span v-text="$t('global.field.id')">ID</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.immeuble.libelle')">Libelle</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.immeuble.adresse')">Adresse</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.immeuble.ville')">Ville</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.immeuble.numero')">Numero</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.immeuble.nbEtages')">Nb Etages</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.immeuble.photo')">Photo</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.immeuble.syndic')">Syndic</span></th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="immeuble in immeubles" :key="immeuble.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'ImmeubleView', params: { immeubleId: immeuble.id } }">{{ immeuble.id }}</router-link>
            </td>
            <td>{{ immeuble.libelle }}</td>
            <td>{{ immeuble.adresse }}</td>
            <td>{{ immeuble.ville }}</td>
            <td>{{ immeuble.numero }}</td>
            <td>{{ immeuble.nbEtages }}</td>
            <td>
              <a v-if="immeuble.photo" v-on:click="openFile(immeuble.photoContentType, immeuble.photo)">
                <img
                  v-bind:src="'data:' + immeuble.photoContentType + ';base64,' + immeuble.photo"
                  style="max-height: 30px"
                  alt="immeuble image"
                />
              </a>
              <span v-if="immeuble.photo">{{ immeuble.photoContentType }}, {{ byteSize(immeuble.photo) }}</span>
            </td>
            <td>
              <div v-if="immeuble.syndic">
                <router-link :to="{ name: 'SyndicView', params: { syndicId: immeuble.syndic.id } }">{{ immeuble.syndic.id }}</router-link>
              </div>
            </td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'ImmeubleView', params: { immeubleId: immeuble.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'ImmeubleEdit', params: { immeubleId: immeuble.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(immeuble)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span id="syndicWebApp.immeuble.delete.question" data-cy="immeubleDeleteDialogHeading" v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-immeuble-heading" v-text="$t('syndicWebApp.immeuble.delete.question', { id: removeId })">
          Are you sure you want to delete this Immeuble?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-immeuble"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeImmeuble()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./immeuble.component.ts"></script>

// src/main/webapp/app/entities/immeuble/immeuble.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IImmeuble } from 'app/shared/model/immeuble.model';
import { getEntities } from './immeuble.reducer';

export const Immeuble = (props: RouteComponentProps<{ url: string }>) => {
  const dispatch = useAppDispatch();

  const immeubleList = useAppSelector(state => state.immeuble.entities);
  const loading = useAppSelector(state => state.immeuble.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  const { match } = props;

  return (
    <div>
      <h2 id="immeuble-heading" data-cy="ImmeubleHeading">
        <Translate contentKey="syndicWebApp.immeuble.home.title">Immeubles</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="syndicWebApp.immeuble.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/immeuble/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="syndicWebApp.immeuble.home.createLabel">Create new Immeuble</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {immeubleList && immeubleList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="syndicWebApp.immeuble.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="syndicWebApp.immeuble.libelle">Libelle</Translate>
                </th>
                <th>
                  <Translate contentKey="syndicWebApp.immeuble.adresse">Adresse</Translate>
                </th>
                <th>
                  <Translate contentKey="syndicWebApp.immeuble.ville">Ville</Translate>
                </th>
                <th>
                  <Translate contentKey="syndicWebApp.immeuble.numero">Numero</Translate>
                </th>
                <th>
                  <Translate contentKey="syndicWebApp.immeuble.nbEtages">Nb Etages</Translate>
                </th>
                <th>
                  <Translate contentKey="syndicWebApp.immeuble.syndic">Syndic</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {immeubleList.map((immeuble, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/immeuble/${immeuble.id}`} color="link" size="sm">
                      {immeuble.id}
                    </Button>
                  </td>
                  <td>{immeuble.libelle}</td>
                  <td>{immeuble.adresse}</td>
                  <td>{immeuble.ville}</td>
                  <td>{immeuble.numero}</td>
                  <td>{immeuble.nbEtages}</td>
                  <td>{immeuble.syndic ? <Link to={`/syndic/${immeuble.syndic.id}`}>{immeuble.syndic.id}</Link> : ''}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/immeuble/${immeuble.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/immeuble/${immeuble.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/immeuble/${immeuble.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="syndicWebApp.immeuble.home.notFound">No Immeubles found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default Immeuble;
