// src/main/webapp/app/entities/revenu/revenu.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="RevenuHeading">
      <span v-text="$t('syndicWebApp.revenu.home.title')" id="revenu-heading">Revenus</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('syndicWebApp.revenu.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'RevenuCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-revenu"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('syndicWebApp.revenu.home.createLabel')"> Create a new Revenu </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && revenus && revenus.length === 0">
      <span v-text="$t('syndicWebApp.revenu.home.notFound')">No revenus found</span>
    </div>
    <div class="table-responsive" v-if="revenus && revenus.length > 0">
      <table class="table table-striped" aria-describedby="revenus">
        <thead>
          <tr>
            <th scope="row"><span v-text="$t('global.field.id')">ID</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.revenu.montant')">Montant</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.revenu.date')">Date</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.revenu.description')">Description</span></th>
            <th scope="row"><span v-text="$t('syndicWebApp.revenu.immeuble')">Immeuble</span></th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="revenu in revenus" :key="revenu.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'RevenuView', params: { revenuId: revenu.id } }">{{ revenu.id }}</router-link>
            </td>
            <td>{{ revenu.montant }}</td>
            <td>{{ revenu.date }}</td>
            <td>{{ revenu.description }}</td>
            <td>
              <div v-if="revenu.immeuble">
                <router-link :to="{ name: 'ImmeubleView', params: { immeubleId: revenu.immeuble.id } }">{{
                  revenu.immeuble.id
                }}</router-link>
              </div>
            </td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'RevenuView', params: { revenuId: revenu.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'RevenuEdit', params: { revenuId: revenu.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(revenu)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span id="syndicWebApp.revenu.delete.question" data-cy="revenuDeleteDialogHeading" v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-revenu-heading" v-text="$t('syndicWebApp.revenu.delete.question', { id: removeId })">
          Are you sure you want to delete this Revenu?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-revenu"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeRevenu()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./revenu.component.ts"></script>

// src/main/webapp/app/entities/revenu/revenu.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IRevenu } from 'app/shared/model/revenu.model';
import { getEntities } from './revenu.reducer';

export const Revenu = (props: RouteComponentProps<{ url: string }>) => {
  const dispatch = useAppDispatch();

  const revenuList = useAppSelector(state => state.revenu.entities);
  const loading = useAppSelector(state => state.revenu.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  const { match } = props;

  return (
    <div>
      <h2 id="revenu-heading" data-cy="RevenuHeading">
        <Translate contentKey="syndicWebApp.revenu.home.title">Revenus</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="syndicWebApp.revenu.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/revenu/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="syndicWebApp.revenu.home.createLabel">Create new Revenu</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {revenuList && revenuList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="syndicWebApp.revenu.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="syndicWebApp.revenu.montant">Montant</Translate>
                </th>
                <th>
                  <Translate contentKey="syndicWebApp.revenu.date">Date</Translate>
                </th>
                <th>
                  <Translate contentKey="syndicWebApp.revenu.description">Description</Translate>
                </th>
                <th>
                  <Translate contentKey="syndicWebApp.revenu.immeuble">Immeuble</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {revenuList.map((revenu, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/revenu/${revenu.id}`} color="link" size="sm">
                      {revenu.id}
                    </Button>
                  </td>
                  <td>{revenu.montant}</td>
                  <td>{revenu.date ? <TextFormat type="date" value={revenu.date} format={APP_LOCAL_DATE_FORMAT} /> : null}</td>
                  <td>{revenu.description}</td>
                  <td>{revenu.immeuble ? <Link to={`/immeuble/${revenu.immeuble.id}`}>{revenu.immeuble.id}</Link> : ''}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/revenu/${revenu.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/revenu/${revenu.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/revenu/${revenu.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="syndicWebApp.revenu.home.notFound">No Revenus found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default Revenu;
